### ISSUE TITLE
cannot find Libraw on your system

### ISSUE THREAD

**Issue by aj178** [mateusz-michalik/cr2-to-jpg#1]
Even though i have installed all the modules that are specified in the requirements, i am not able to run the script. 
![capture](https://user-images.githubusercontent.com/36670990/48570564-e66f6080-e904-11e8-9c5e-9f6a5c4a38e5.PNG)
it will be helpful if I get some solution to this issue.
Thanks

**Comment by nax3t** [comment]
Use [LibRaw 0.18](https://www.libraw.org/download) (scroll down past current version or use this [link](https://www.libraw.org/data/LibRaw-0.18.13.zip))
See [here](https://www.libraw.org/docs/Install-LibRaw-eng.html) for installation instructions on Windows (bottom of page).

If that doesn't work then you may need to double check that it's in your path (just a guess).
Also, be sure to restart command line after installation and prior to running the python file.

**Comment by matthalvorson33** [comment]
did you ever get this working? I'm stuck on the same issue and feel like I'm going crazy, I've validated the libraw files are in the right place and installed, tried with both LibRaw 0.18 and the newer version. Python is able to import libraw no problem, but util.find_library('raw') in bindings.py fails so I'm getting the same ImportError shown in your screenshot

**Comment by anaym** [comment]
@matthalvorson33 
Possible hotfix:
1) Download libraw v0.19
2) Move libraw.dll from `LibRaw-0.19.2-Win64\LibRaw-0.19.2\bin` to your python-script directory
3) Modify `%HOMEDRIVE%%HOMEPATH%\AppData\Local\Programs\Python\Python37\Lib\site-packages\libraw\bindings.py`:
`libraw = util.find_library('raw')` to `libraw = 'libraw.dll'`
`17: structs_17,` to `19: structs_17,`

**Comment by pvbecker** [comment]
i know it's been quite a while, but i've ran into this problem these days.
what solved for me was to clone libraw repository (https://github.com/LibRaw/LibRaw), checkout to 19.0-release branch and compile it using the steps described in the projetc's website (Native Building on windows section, https://www.libraw.org/docs/Install-LibRaw-eng.html).
Then, proceed to clone the rawkit project repository (https://github.com/photoshell/rawkit) and straight up copy the folders /libraw and /rawkit into the directory in which pip installs the add-ons for python.
Also you'll need to either add the path for the libraw.dll into your system environment or edit the bindings.py from rawkit in order for it to find the dll's location.
Hope it helps.

**Comment by mateusz-michalik** [comment]
Everyone, I only just saw these. I had no idea that issues were raised on this repo! Closing it as I can see there are some fixes above for Windows users.

**Comment by lucasmacad** [comment]
> @matthalvorson33
> Possible hotfix:
> 
> 1. Download libraw v0.19
> 2. Move libraw.dll from `LibRaw-0.19.2-Win64\LibRaw-0.19.2\bin` to your python-script directory
> 3. Modify `%HOMEDRIVE%%HOMEPATH%\AppData\Local\Programs\Python\Python37\Lib\site-packages\libraw\bindings.py`:
>    `libraw = util.find_library('raw')` to `libraw = 'libraw.dll'`
>    `17: structs_17,` to `19: structs_17,`

Hi there,

Been struggling myself with Python giving me an ImportError for an Unsupported Libraw version: 0.20.2.
Adapted your approach above to edit the bindings.py file and change '18: structs_18,' to '20: structs_18,' which fixed my problem and the code is now working & I can use rawkit!

Cheers,
L
